[package]
name = "pam_proxy_helper"
author = "Manuel Frischknecht"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam-client = "0.5.0"